### ISSUE TITLE
Fix CI reporting

### ISSUE THREAD

**Issue by Iluvmagick** [NilFoundation/placeholder#10]

**Comment by AndreyMlashkin** [comment]
Could you provide more Infos?

**Comment by Iluvmagick** [comment]
We used to have a cool widget, iirc made by @x-mass, which told the amount of failed/passing tests, and linked to the failed tests in CI.
It greatly simplified figuring out what exactly out of all the tests I broke.

**Comment by Iluvmagick** [comment]
![image](https://github.com/user-attachments/assets/af7ca9ad-b2cc-4c33-ab3b-04ce5ef6bdba)

**Comment by AndreyMlashkin** [comment]
I also liked that widget, but on some point, I was explicitly told to remove it...
@knazarov @akokoshn

**Comment by Iluvmagick** [comment]
Thanks for adding it back!
It's very nice.
